name: Update WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"  # Esegue ogni giorno a mezzanotte UTC
  workflow_dispatch:     # Consente di avviarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
